spring:
  application:
    name: cavosh

  datasource:
    url: jdbc:postgresql://127.0.0.1:${POSTGRES_PORT:5432}/${POSTGRES_DB:cavosh}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration

  security:
    jwt:
      secret-base64: ${JWT_SECRET}
      issuer: ${JWT_ISSUER:cavosh-auth}
      audience: ${JWT_AUDIENCE:cavosh-api}
      access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:15m}